# Site settings
title: Jerry's cheatsheet
email: phoibos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my awesome blog.
baseurl:  # the subpath of your site, e.g. /blog
#url: "https://rmsubekti.github.io" # the base hostname & protocol for your site
#google_analytics: #your GA unique id, e.g. UA-xxxxxxxx-x
#disqus_username: #Your disqus_username to add comments on the post

# Optional settings
github: #your github username
linkedin: #linkedin username



# Build settings
markdown: kramdown

sass:
    style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink : '/:year/:title/'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 5
paginate_path: 'p/:num'
